version: "3.9"

services:
  cluster:
    build:
      context: ./dxspider
      dockerfile: Dockerfile
      args:
        - IMAGE=alpine
        - IMAGE_TAG=latest
        - SPIDER_VERSION=mojo # or of HEAD
    volumes:
      - cluster_data:/spider
    env_file:
      - prod.env
    ports:
      - 7300:7300
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  cluster_data:
