version: "3.9"

services:
  cluster:
    build:
      context: ./dxspider
      dockerfile: Dockerfile
      args:
        - SPIDER_VERSION=mojo
    volumes:
      - cluster_local_cmd_data:/spider/local_cmd
      - cluster_connect_data:/spider/connect
      - cluster_scripts_data:/spider/scripts
    env_file:
      - prod.env
    ports:
      - 7300:7300
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  cluster_local_cmd_data:
  cluster_connect_data:
  cluster_scripts_data:
